development:
  adapter: postgresql
  database: people_development
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  database: people_test
  pool: 5
  timeout: 5000
  host: localhost
